import bcrypt from "bcryptjs";
import { env } from "../config/env.js";
import { pool } from "./pool.js";
import { storageProvider } from "../storage/local-storage.js";
import { createUploadedFile } from "../services/files.service.js";

export type SeedProfile = "admin_only" | "demo";

const seedAdminEmail = process.env.SEED_ADMIN_EMAIL ?? "admin@adfix.local";
const seedAdminName = process.env.SEED_ADMIN_NAME ?? "Adfix Admin";
const seedAdminPassword = process.env.SEED_ADMIN_PASSWORD ?? "ChangeMe123!";
const seedDemoUserPassword = process.env.SEED_DEMO_USER_PASSWORD ?? "DemoUser123!";

const demoUsers = [
  { email: "manager@adfix.local", name: "Project Manager" },
  { email: "designer@adfix.local", name: "Creative Designer" },
  { email: "editor@adfix.local", name: "Video Editor" },
  { email: "coordinator@adfix.local", name: "Project Coordinator" },
  { email: "viewer@adfix.local", name: "Read Only Viewer" }
];
const demoClientUser = { email: "client@adfix.local", name: "Demo Client Reviewer" };

async function ensureAdminUser() {
  const passwordHash = await bcrypt.hash(seedAdminPassword, 12);

  await pool.query(
    `
    INSERT INTO users (email, name, password_hash, is_active, is_admin)
    VALUES ($1, $2, $3, TRUE, TRUE)
    ON CONFLICT (email)
    DO UPDATE
      SET name = EXCLUDED.name,
          password_hash = EXCLUDED.password_hash,
          is_active = TRUE,
          is_admin = TRUE,
          deleted_at = NULL,
          updated_at = NOW()
    `,
    [seedAdminEmail, seedAdminName, passwordHash]
  );

  console.log(`Seeded admin user: ${seedAdminEmail}`);
}

async function ensureDemoUsers() {
  const passwordHash = await bcrypt.hash(seedDemoUserPassword, 12);

  for (const user of demoUsers) {
    await pool.query(
      `
      INSERT INTO users (email, name, password_hash, is_active, is_admin, account_type)
      VALUES ($1, $2, $3, TRUE, FALSE, 'staff')
      ON CONFLICT (email)
      DO UPDATE
        SET name = EXCLUDED.name,
            password_hash = EXCLUDED.password_hash,
            is_active = TRUE,
            is_admin = FALSE,
            account_type = 'staff',
            deleted_at = NULL,
            updated_at = NOW()
      `,
      [user.email, user.name, passwordHash]
    );
  }

  console.log(`Seeded ${demoUsers.length} demo users`);

  await pool.query(
    `INSERT INTO users (email, name, password_hash, is_active, is_admin, account_type)
     VALUES ($1, $2, $3, TRUE, FALSE, 'client')
     ON CONFLICT (email) DO UPDATE SET
       name = EXCLUDED.name, password_hash = EXCLUDED.password_hash,
       is_active = TRUE, is_admin = FALSE, account_type = 'client', deleted_at = NULL, updated_at = NOW()`,
    [demoClientUser.email, demoClientUser.name, passwordHash]
  );
  console.log(`Seeded demo client user: ${demoClientUser.email}`);
}

async function seedDemoData() {
  const adminUser = await pool.query<{ id: string }>(
    "SELECT id FROM users WHERE email = $1 AND deleted_at IS NULL",
    [seedAdminEmail]
  );
  const adminId = adminUser.rows[0]?.id;
  if (!adminId) throw new Error("Admin user was not found after seeding.");

  const existingClient = await pool.query<{ id: string }>(
    "SELECT id FROM clients WHERE email = 'demo.client@adfix.local' AND deleted_at IS NULL LIMIT 1"
  );
  let clientId = existingClient.rows[0]?.id;

  if (!clientId) {
    const inserted = await pool.query<{ id: string }>(`
      INSERT INTO clients (name, company, email, notes)
      VALUES ('Demo Client', 'Adfix Demo Co', 'demo.client@adfix.local', 'Generated by demo seed profile')
      RETURNING id
    `);
    clientId = inserted.rows[0]?.id;
  }

  if (!clientId) throw new Error("Failed to create or fetch demo client.");

  const existingProject = await pool.query<{ id: string }>(
    "SELECT id FROM projects WHERE client_id = $1 AND name = 'Demo Project' AND deleted_at IS NULL LIMIT 1",
    [clientId]
  );
  let projectId = existingProject.rows[0]?.id;

  if (!projectId) {
    const inserted = await pool.query<{ id: string }>(
      `
      INSERT INTO projects (
        client_id, name, description, current_phase, priority, start_date, deadline, created_by
      )
      VALUES (
        $1, 'Demo Project', 'Demo seeded project for local development', 'strategy_planning', 'high',
        CURRENT_DATE, CURRENT_DATE + INTERVAL '30 days', $2
      )
      RETURNING id
      `,
      [clientId, adminId]
    );
    projectId = inserted.rows[0]?.id;
  }

  if (!projectId) throw new Error("Failed to create or fetch demo project.");

  const existingTaskCount = await pool.query<{ count: string }>(
    "SELECT COUNT(*)::text AS count FROM tasks WHERE project_id = $1 AND deleted_at IS NULL",
    [projectId]
  );

  if (Number(existingTaskCount.rows[0]?.count ?? 0) === 0) {
    await pool.query(
      `
      INSERT INTO tasks (project_id, title, description, phase, status, priority, created_by)
      VALUES
        ($1, 'Kickoff call', 'Initial stakeholder kickoff meeting', 'strategy_planning', 'completed', 'high', $2),
        ($1, 'Creative brief draft', 'Prepare first draft for internal review', 'strategy_planning', 'in_progress', 'high', $2),
        ($1, 'Content requirements', 'Collect assets and copy requirements', 'production', 'pending', 'medium', $2)
      `,
      [projectId, adminId]
    );
  }

  const clientUserResult = await pool.query<{ id: string }>(
    "SELECT id FROM users WHERE email = $1 AND deleted_at IS NULL",
    [demoClientUser.email]
  );
  const clientUserId = clientUserResult.rows[0]?.id;
  if (!clientUserId) throw new Error("Demo client user was not found after seeding.");
  await pool.query(
    `INSERT INTO client_memberships (client_id, user_id, role)
     VALUES ($1, $2, 'reviewer') ON CONFLICT (client_id, user_id) DO UPDATE SET role = 'reviewer'`,
    [clientId, clientUserId]
  );

  const existingDeliverable = await pool.query<{ id: string }>(
    "SELECT id FROM deliverables WHERE project_id = $1 AND title = 'Campaign concept deck' AND deleted_at IS NULL",
    [projectId]
  );
  if (!existingDeliverable.rows[0]) {
    const stored = await storageProvider.save({
      fileName: "campaign-concept-v1.txt",
      buffer: Buffer.from("Adfix demo campaign concept — version 1\nPrepared for client review.", "utf8")
    });
    const file = await createUploadedFile({
      projectId,
      fileName: "campaign-concept-v1.txt",
      fileType: "deliverable",
      storageType: "local",
      objectKey: stored.objectKey,
      mimeType: "text/plain",
      fileSize: stored.size,
      checksumSha256: stored.checksumSha256,
      uploadedBy: adminId
    });
    const deliverable = await pool.query<{ id: string }>(
      `INSERT INTO deliverables (project_id, title, description, status, created_by)
       VALUES ($1, 'Campaign concept deck', 'Initial creative direction for client review', 'in_review', $2)
       RETURNING id`,
      [projectId, adminId]
    );
    await pool.query(
      `INSERT INTO deliverable_versions (deliverable_id, file_id, version_number, submission_note, submitted_by)
       VALUES ($1, $2, 1, 'First concept version', $3)`,
      [deliverable.rows[0].id, file.id, adminId]
    );
  }

  console.log("Seeded demo data profile");
}

export async function seedDatabase(profile: SeedProfile = env.SEED_PROFILE) {
  await ensureAdminUser();

  if (profile === "demo") {
    await ensureDemoUsers();
    await seedDemoData();
  }
}
